// Package modelsold contains the types for schema 'public'.
package trash

import (
	"github.com/jinzhu/gorm"
	"net/url"
	"restProject/model"
)

// Code generated by xo. DO NOT EDIT.

// Municipio represents a row from 'public.municipio'.
type Municipio struct {
	Estado string `json:"estado"` // estado
	Cidade string `json:"cidade"` // cidade
	Codigo int `json:"codigo"` // codigo
}

func (o *Municipio) Search(db *gorm.DB, values url.Values) *gorm.DB {
	return model.Search(db, values)
}
